version: 2.1

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
      
sphinx: 
  fail_on_warning: true

formats: 
  - pdf 
  - epub
# version: 2 

# build:
#   os: "ubuntu-20.04"
#   tools: 
#     python: "3.7"
# #       install:
# #         - method: pip
# #           path: .

# sphinx: 
#   fail_on_warning: true

